# Generated by Django 5.2.6 on 2025-09-22 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_recruiter", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("RECRUITERS", "Recruiters only"),
                            ("PRIVATE", "Private"),
                        ],
                        default="RECRUITERS",
                        max_length=12,
                    ),
                ),
                ("show_email_to_recruiters", models.BooleanField(default=False)),
                ("show_phone_to_recruiters", models.BooleanField(default=False)),
                ("show_resume_to_recruiters", models.BooleanField(default=False)),
                ("show_education_to_recruiters", models.BooleanField(default=False)),
                ("show_experience_to_recruiters", models.BooleanField(default=False)),
                ("headline", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("education", models.TextField(blank=True)),
                ("experience", models.TextField(blank=True)),
                ("resume_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
