# Generated by Django 5.0 on 2025-09-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_location_profile_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_LastName_to_recruiters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_firstName_to_recruiters',
            field=models.BooleanField(default=False),
        ),
    ]
