# Generated by Django 5.0 on 2025-09-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='show_LastName_to_recruiters',
            new_name='show_lastName_to_recruiters',
        ),
    ]
