# Generated by Django 5.0 on 2025-10-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_last_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
