# Generated by Django 5.0 on 2025-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_description_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
