# Generated by Django 5.0 on 2025-09-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(default='', max_length=128),
        ),
    ]
