# Generated by Django 5.2.6 on 2025-10-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateRecommendation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("match_score", models.IntegerField(default=0)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_for_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_recommendations",
                        to="home.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "-match_score"],
                        name="home_candid_job_id_6104e7_idx",
                    ),
                    models.Index(
                        fields=["candidate"], name="home_candid_candida_c35cdd_idx"
                    ),
                ],
                "unique_together": {("job", "candidate")},
            },
        ),
        migrations.CreateModel(
            name="JobRecommendation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("match_score", models.IntegerField(default=0)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_to_candidates",
                        to="home.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "-match_score"],
                        name="home_jobrec_candida_7deca6_idx",
                    ),
                    models.Index(fields=["job"], name="home_jobrec_job_id_a5a028_idx"),
                ],
                "unique_together": {("candidate", "job")},
            },
        ),
    ]
