# Generated by Django 5.0 on 2025-10-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_candidaterecommendation_jobrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEW', 'Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=16),
        ),
    ]
