# Generated by Django 5.2.6 on 2025-10-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("SCREENING", "Screening"),
                    ("INTERVIEW", "Interview"),
                    ("OFFER", "Offer"),
                    ("HIRED", "Hired"),
                    ("REJECTED", "Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=16,
            ),
        ),
    ]
