# Generated by Django 5.2.6 on 2025-10-21 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_application_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedCandidateSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Search text across headline/skills/projects",
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("min_years_experience", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_candidate_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedCandidateMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                ("seen", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_search_hits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="home.savedcandidatesearch",
                    ),
                ),
            ],
            options={
                "ordering": ["-matched_at"],
            },
        ),
        migrations.AddIndex(
            model_name="savedcandidatesearch",
            index=models.Index(
                fields=["owner", "is_active"], name="home_savedc_owner_i_1b78b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedcandidatematch",
            index=models.Index(
                fields=["search", "seen", "-matched_at"],
                name="home_savedc_search__11ff69_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedcandidatematch",
            unique_together={("search", "candidate")},
        ),
    ]
