# Generated by Django 4.2.26 on 2025-11-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_savedcandidatesearch_savedcandidatematch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
