# Generated by Django 5.2.8 on 2025-11-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_job_latitude_job_longtitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="applicant_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant_location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
