# Generated by Django 4.2.26 on 2025-11-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_application_applicant_lat_application_applicant_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
